### ISSUE TITLE
 Migrate starting services from daemon package to systemd config

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/spacy-services.deb#7]
The old Debian package "daemon" used for starting services in init.d start script causes problems on newer Debian and Ubuntu releases, since stopping/restarting the services doesn't work.

Migrate to modern systemd config.

Additionally systemctl status opensemanticsearch will show infos.

**Comment by Mandalka** [comment]
Migrated to systemd config file: https://github.com/opensemanticsearch/spacy-services.deb/commit/d03b767ce174707edf3cbeb4c68ccc6ce12bac14
