### ISSUE TITLE
missing docker file

### ISSUE THREAD

**Issue by ghost** [opensemanticsearch/spacy-services.deb#8]
Hi,

Hope you are all well !

Sounds like it is missing the dockerfile because even the opensemanticsearch/spacy-services image is not pullable and I can docker-compose up opensemanticsearch.

Is it possible to push it for both hub.docker.com for the image and github.com for the Dockerfile ?

Cheers,
X

**Comment by Mandalka** [comment]
The Dockerfile is in https://github.com/opensemanticsearch/spacy-services/blob/master/Dockerfile and the image is build automatically if you do a <code>docker-compose build</code> in main repo open-semantic-search.

It will be on ducker hub, too soon by https://github.com/opensemanticsearch/open-semantic-search/issues/390
